In [1]:
# Import the pandas library
import pandas as pd

In [2]:
# Load the dataset from the provided URL
df = pd.read_csv('https://afterwork.ai/ds/e/healthcare_as6of.csv')

# Display the dataset to understand its structure
df.head()

,Patient ID,Patient Name,Age,Gender,Diagnosis,Treatment,Admission Date,Discharge Date,Doctor Name,Hospital
0,1001,John Doe,45,Male,Hypertension,Medication,2021-05-10,2021-05-15,Dr. Smith,General Hospital
1,1002,Jane Smith,30,Female,Diabetes,Diet and Exercise,2021-06-02,2021-06-10,Dr. Johnson,Community Clinic
2,1003,Michael Johnson,55,Male,Arthritis,Physical Therapy,2021-04-20,2021-05-05,Dr. Brown,Regional Medical Center
3,1004,Sarah Lee,40,Female,Migraine,Medication and Rest,2021-07-12,2021-07-20,Dr. Wilson,University Hospital
4,1005,David Wilson,65,Male,Heart Disease,Cardiac Surgery,2021-03-15,2021-04-10,Dr. Adams,City Medical Center

In [15]:
# Filter the dataset based on multiple conditions
filtered_data = df[((df["Age"]<=40)&(df["Treatment"].str.contains("Therapy"))) & (df["Hospital"]!="General Hospital")]

#display the filtered data

filtered_data

,Patient ID,Patient Name,Age,Gender,Diagnosis,Treatment,Admission Date,Discharge Date,Doctor Name,Hospital
7,1008,Lisa Taylor,35,Female,Pneumonia,Antibiotics and Oxygen Therapy,2021-09-01,2021-09-10,Dr. White,Community Hospital
11,1012,Samantha King,33,Female,Depression,Therapy and Medication,2021-12-05,2021-12-15,Dr. Harris,Metro General Hospital
19,1020,Oliver Scott,29,Male,Sleep Apnea,CPAP Therapy,2021-02-10,2021-02-20,Dr. Lopez,City General Clinic
22,1023,Ava Rivera,31,Female,PTSD,Therapy and Support Groups,2021-11-10,2021-11-20,Dr. Patel,Community Wellness Clinic
35,1036,Logan Nguyen,27,Male,Depression,Therapy and Medication,2021-10-05,2021-10-15,Dr. Stewart,Metro Health Clinic
44,1045,Charlotte Kim,31,Female,Depression,Therapy and Medication,2021-01-05,2021-01-15,Dr. Nguyen,City General Clinic
52,1053,Sophia Rivera,30,Female,Arthritis,Physical Therapy and Pain Management,2021-05-01,2021-05-10,Dr. Patel,Community Wellness Clinic
54,1055,Mia Kim,35,Female,Chronic Pain,Physical Therapy and Pain Management,2021-03-15,2021-03-25,Dr. Nguyen,City Wellness Center
58,1059,Amelia Price,29,Female,Diabetes,Diet and Insulin Therapy,2021-11-10,2021-11-20,Dr. Evans,Regional General Clinic
62,1063,Evelyn Rivera,38,Female,Depression,Therapy and Medication,2021-07-10,2021-07-20,Dr. Patel,Community Clinic
71,1072,Logan Ward,36,Male,Depression,Therapy and Medication,2021-10-05,2021-10-15,Dr. Rivera,Metro Health Clinic

In [16]:
# Standardizing Column Names

# Load the dataset from the provided URL
df = pd.read_csv('https://afterwork.ai/ds/e/healthcare_5i3x9.csv')
df.head()

,Patient ID,Gender,Age,Diagnosis,Blood Type,Medication,Allergies,Admission Date,Discharge Date,Doctor
0,1001,Male,45,Hypertension,A+,Lisinopril,NaN,2021-05-10,2021-05-15,Dr. Smith
1,1002,Female,32,Diabetes,O-,Metformin,Peanuts,2021-06-02,2021-06-10,Dr. Johnson
2,1003,Male,60,Arthritis,B+,Ibuprofen,Penicillin,2021-07-15,2021-07-25,Dr. Brown
3,1004,Female,28,Asthma,AB-,Albuterol,Dust,2021-08-03,2021-08-12,Dr. Lee
4,1005,Male,50,Heart Disease,A-,Atorvastatin,Shellfish,2021-09-20,2021-09-30,Dr. Martinez

In [ ]:
#Standardize column names by converting to lowercase and replacing spaces with underscores

df.columns = df.columns.str.lower().str.replace(" ","_")

df.head()

,patient_id,gender,age,diagnosis,blood_type,medication,allergies,admission_date,discharge_date,doctor
0,1001,Male,45,Hypertension,A+,Lisinopril,NaN,2021-05-10,2021-05-15,Dr. Smith
1,1002,Female,32,Diabetes,O-,Metformin,Peanuts,2021-06-02,2021-06-10,Dr. Johnson
2,1003,Male,60,Arthritis,B+,Ibuprofen,Penicillin,2021-07-15,2021-07-25,Dr. Brown
3,1004,Female,28,Asthma,AB-,Albuterol,Dust,2021-08-03,2021-08-12,Dr. Lee
4,1005,Male,50,Heart Disease,A-,Atorvastatin,Shellfish,2021-09-20,2021-09-30,Dr. Martinez

In [90]:
#Handling Missing Data in Pandas

# Load the dataset from the provided URL
df1 = pd.read_csv('https://afterwork.ai/ds/e/healthcare_nqob7.csv')

# Display the dataset to check for missing values
df1.isnull().sum()

Patient ID         0
Age                0
Gender             0
Height             0
Weight             1
Blood Pressure     2
Cholesterol        1
Diabetes           0
Smoker             0
Medication        18
dtype: int64

In [92]:
# Fill missing values in the 'Weight' column with the mean value of the column

df1["Weight"].fillna(df1["Weight"].mean())

df1.isnull().sum()

Patient ID         0
Age                0
Gender             0
Height             0
Weight             0
Blood Pressure     2
Cholesterol        1
Diabetes           0
Smoker             0
Medication        18
dtype: int64

In [32]:
# Drop rows with any missing values in the dataset
df1.dropna(axis=0,how="any",inplace=True)
df1.isnull().sum()

Patient ID        0
Age               0
Gender            0
Height            0
Weight            0
Blood Pressure    0
Cholesterol       0
Diabetes          0
Smoker            0
Medication        0
dtype: int64

In [34]:
# Load the dataset from the provided URL
df2 = pd.read_csv('https://afterwork.ai/ds/ch/healthcare_4ywuo.csv')

# Display the dataset to check for missing values
df.isnull().sum()

# drop all the null values

df2.dropna(axis=0,how="all",inplace=True)

In [35]:
df2.head()

,Patient ID,Age,Gender,Height,Weight,Blood Type,Cholesterol Level,Heart Rate,Blood Pressure,Temperature
0,1001,45,Male,175,70,A,200.0,75.0,120/80,98.6
1,1002,32,Female,160,55,B,180.0,NaN,110/70,NaN
2,1003,60,Male,180,85,O,NaN,70.0,130/90,NaN
3,1004,28,Female,165,60,AB,190.0,80.0,NaN,NaN
4,1005,50,Male,170,75,A,220.0,72.0,125/85,NaN

In [50]:
#View Rows with ANY Missing Values

df2[df2.isna().any(axis=1)].sort_values(by=["Age","Weight"],ascending=[False,True])

,Patient ID,Age,Gender,Height,Weight,Blood Type,Cholesterol Level,Heart Rate,Blood Pressure,Temperature
2,1003,60,Male,180,85,O,NaN,70.0,130/90,NaN
6,1007,55,Male,178,80,O,210.0,78.0,135/90,NaN
4,1005,50,Male,170,75,A,220.0,72.0,125/85,NaN
8,1009,48,Male,172,78,A,NaN,74.0,122/82,NaN
7,1008,42,Female,163,58,AB,195.0,76.0,118/78,NaN
5,1006,38,Female,155,50,B,NaN,68.0,115/75,NaN
9,1010,35,Female,158,52,B,185.0,71.0,112/72,NaN
1,1002,32,Female,160,55,B,180.0,NaN,110/70,NaN
3,1004,28,Female,165,60,AB,190.0,80.0,NaN,NaN

In [53]:
#Statistical Analysis with Pandas

# Loading the dataset from the provided URL
df = pd.read_csv('https://afterwork.ai/ds/ch/healthcare_t7g0s.csv')

# Displaying the first few rows of the dataset
df.head()

,Patient ID,Age,Gender,Diagnosis,Treatment,Medication,Lab Results,Doctor Visit Date,Hospital Name,Insurance Coverage
0,1001,45,Male,Hypertension,Medication A,Drug X,Normal,2021-05-10,Hospital A,Full Coverage
1,1002,32,Female,Diabetes,Diet and Exercise,Insulin,High,2021-06-15,Hospital B,Partial Coverage
2,1003,50,Male,Arthritis,Physical Therapy,Pain Relievers,Normal,2021-04-20,Hospital C,No Coverage
3,1004,28,Female,Allergies,Medication B,Antihistamines,Normal,2021-07-05,Hospital A,Full Coverage
4,1005,65,Female,Osteoporosis,Medication C,Calcium Supplements,Low,2021-03-30,Hospital D,Partial Coverage

In [54]:
# Generating summary statistics using .describe()

df.describe()

        Patient ID        Age
count    75.000000  75.000000
mean   1038.000000  47.533333
std      21.794495  13.172795
min    1001.000000  27.000000
25%    1019.500000  36.500000
50%    1038.000000  46.000000
75%    1056.500000  58.000000
max    1075.000000  73.000000

In [57]:
# Performing statistical analysis on grouped data by 'Insurance Coverage' and calculating mean age for each group using .groupby()

df.groupby("Insurance Coverage").describe()

                   Patient ID                                           \
                        count         mean        std     min      25%
Insurance Coverage
Full Coverage            32.0  1038.406250  21.888072  1001.0  1021.25
No Coverage              14.0  1036.000000  21.722020  1003.0  1018.75
Partial Coverage         29.0  1038.517241  22.436610  1002.0  1020.00

                                              Age                              \
                       50%      75%     max count       mean        std   min
Insurance Coverage
Full Coverage       1039.0  1056.50  1074.0  32.0  48.625000  12.193996  28.0
No Coverage         1035.5  1052.25  1069.0  14.0  49.285714  12.952152  29.0
Partial Coverage    1039.0  1057.00  1075.0  29.0  45.482759  14.450953  27.0


                      25%   50%    75%   max
Insurance Coverage
Full Coverage       40.75  47.5  56.00  73.0
No Coverage         39.25  48.5  57.75  70.0
Partial Coverage    33.00  40.0  59.00  73.0

In [63]:
#Data Filtering with iloc Slicing
# Load the dataset from the provided URL
df = pd.read_csv('https://afterwork.ai/ds/e/healthcare_u1ykc.csv')


# Extracting rows 2 to 5 (indexing starts from 0) and columns 1 to 4 (indexing starts from 0)

filtered_data = df.iloc[1:5,1:5].reset_index()
filtered_data

   index  Gender  Age  Diagnosis         Treatment
0      1  Female   30   Diabetes      Diet Control
1      2    Male   60  Arthritis  Physical Therapy
2      3  Female   25  Influenza              Rest
3      4    Male   35  Allergies      Medication B

In [64]:
#Date Range Filtering
# Load the dataset from the provided URL
df = pd.read_csv('https://afterwork.ai/ds/ch/healthcare_u75x4.csv')
df.head()

,Patient ID,Patient Name,Age,Gender,Diagnosis,Treatment,Admission Date,Discharge Date,Doctor Name,Hospital
0,1001,Emily Johnson,45,Female,Hypertension,Medication,2021-05-10,2021-05-15,Dr. Smith,General Hospital
1,1002,David Brown,32,Male,Influenza,Rest and Fluids,2021-06-20,2021-06-25,Dr. Lee,Community Clinic
2,1003,Sarah Wilson,50,Female,Diabetes,Diet and Exercise,2021-07-05,2021-07-12,Dr. Patel,Regional Medical Center
3,1004,James Miller,65,Male,Arthritis,Physical Therapy,2021-08-15,2021-08-30,Dr. Garcia,University Hospital
4,1005,Linda Davis,38,Female,Migraine,Medication and Rest,2021-09-10,2021-09-17,Dr. Wong,City Medical Center

In [73]:
# Convert 'Admission Date' column to datetime format

df["Admission Date"] = pd.to_datetime(df["Admission Date"])
#verify the data type
print(df["Admission Date"].dtype)

df["Discharge Date"] = pd.to_datetime(df["Discharge Date"])

print(df.dtypes)

datetime64[ns]
Patient ID                 int64
Patient Name              object
Age                        int64
Gender                    object
Diagnosis                 object
Treatment                 object
Admission Date    datetime64[ns]
Discharge Date    datetime64[ns]
Doctor Name               object
Hospital                  object
dtype: object

In [81]:
# Apply date range filtering to focus on data within the specified range

df[((df["Discharge Date"] - df["Admission Date"])>pd.Timedelta(weeks=3)) & (df["Gender"]=="Male")]

,Patient ID,Patient Name,Age,Gender,Diagnosis,Treatment,Admission Date,Discharge Date,Doctor Name,Hospital
11,1012,Christopher Young,70,Male,Cancer,Chemotherapy,2022-04-15,2022-05-10,Dr. Stewart,Oncology Center
33,1034,Nolan Fisher,66,Male,Alzheimer's Disease,Memory Care Program,2024-04-15,2024-05-10,Dr. Fisher,Memory Wellness Center
55,1056,Jack Fisher,67,Male,Alzheimer's Disease,Memory Care Program,2026-04-15,2026-05-10,Dr. Fisher,Memory Wellness Center

In [82]:
df = pd.read_csv('https://afterwork.ai/ds/ch/healthcare_6pkji.csv')
df.head()

,Patient ID,Gender,Age,Diagnosis,Treatment,Medication,Admission Date,Discharge Date,Doctor Name,Hospital
0,1001,Male,45,Hypertension,Medication A,Aspirin,2021-05-10,2021-05-15,Dr. Smith,General Hospital
1,1002,Female,30,Diabetes,Diet and Exercise,Metformin,2021-06-02,2021-06-10,Dr. Johnson,Community Clinic
2,1003,Male,60,Arthritis,Physical Therapy,Ibuprofen,2021-04-20,2021-05-05,Dr. Brown,Regional Medical Center
3,1004,Female,55,Depression,Therapy,SSRI,2021-07-12,2021-07-25,Dr. Lee,Psychiatric Hospital
4,1005,Male,35,Influenza,Rest and Fluids,Acetaminophen,2021-08-05,2021-08-10,Dr. Wilson,General Hospital

In [86]:

# column standardization
df.columns = df.columns.str.lower().str.replace(" ","_")


# Filtering out patients diagnosed with 'Diabetes' and received treatment 'Diet and Exercise'

filtered_data = df.query("`diagnosis` == 'Diabetes' and `treatment` == 'Diet and Exercise'")

filtered_data

,patient_id,gender,age,diagnosis,treatment,medication,admission_date,discharge_date,doctor_name,hospital
1,1002,Female,30,Diabetes,Diet and Exercise,Metformin,2021-06-02,2021-06-10,Dr. Johnson,Community Clinic

In [87]:
#Data Loading Optimization

# Define the URL for the dataset
df = pd.read_csv('https://afterwork.ai/ds/e/healthcare_zft9i.csv')

# Display DataFrame information

df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient ID      75 non-null     int64
 1   Patient Name    75 non-null     object
 2   Age             75 non-null     int64
 3   Gender          75 non-null     object
 4   Diagnosis       75 non-null     object
 5   Treatment       75 non-null     object
 6   Admission Date  75 non-null     object
 7   Discharge Date  75 non-null     object
 8   Doctor Name     75 non-null     object
 9   Hospital        75 non-null     object
dtypes: int64(2), object(8)
memory usage: 37.6 KB

In [88]:
df.shape

(75, 10)

In [89]:
url = "https://afterwork.ai/ds/e/healthcare_zft9i.csv"

chucks = pd.read_csv(url,chunksize=5)

optimized_data = pd.concat(chucks)

optimized_data.info(memory_usage ="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient ID      75 non-null     int64
 1   Patient Name    75 non-null     object
 2   Age             75 non-null     int64
 3   Gender          75 non-null     object
 4   Diagnosis       75 non-null     object
 5   Treatment       75 non-null     object
 6   Admission Date  75 non-null     object
 7   Discharge Date  75 non-null     object
 8   Doctor Name     75 non-null     object
 9   Hospital        75 non-null     object
dtypes: int64(2), object(8)
memory usage: 37.6 KB