In [ ]:
# Importing the Pandas library
import pandas as pd

# Loading the dataset from the provided URL

df = pd.read_csv('https://afterwork.ai/ds/e/healthcare_and_pharmaceuticals_hjvuy.csv')

# Selecting specific data columns for analysis
# 'Patient Name', 'Age', 'Diagnosis', 'Treatment', 'Medication', 'Doctor'

print(df.head())

new_data = df[['Patient Name', 'Age', 'Diagnosis', 'Treatment', 'Medication', 'Doctor']]

# Displaying the selected data
new_data.head()

   Patient ID   Patient Name  Age  Gender      Diagnosis  \
0       12345       John Doe   45    Male       Diabetes
1       23456     Jane Smith   35  Female   Hypertension
2       34567  Michael Brown   50    Male      Arthritis
3       45678    Emily Davis   28  Female        Allergy
4       56789   David Wilson   60    Male  Heart Disease

                   Treatment   Medication Admission Date Discharge Date  \
0            Insulin Therapy    Metformin     2022-01-15     2022-01-30
1  Blood Pressure Monitoring   Lisinopril     2022-02-05     2022-02-20
2           Physical Therapy     Naproxen     2022-03-10     2022-03-25
3             Antihistamines  Fluticasone     2022-04-01     2022-04-15
4     Cardiac Rehabilitation      Aspirin     2022-05-05     2022-05-20

         Doctor
0     Dr. Smith
1   Dr. Johnson
2  Dr. Williams
3  Dr. Anderson
4  Dr. Martinez
    Patient Name  Age      Diagnosis                  Treatment   Medication  \
0       John Doe   45       Diabetes            Insulin Therapy    Metformin
1     Jane Smith   35   Hypertension  Blood Pressure Monitoring   Lisinopril
2  Michael Brown   50      Arthritis           Physical Therapy     Naproxen
3    Emily Davis   28        Allergy             Antihistamines  Fluticasone
4   David Wilson   60  Heart Disease     Cardiac Rehabilitation      Aspirin

         Doctor
0     Dr. Smith
1   Dr. Johnson
2  Dr. Williams
3  Dr. Anderson
4  Dr. Martinez

In [4]:
cleaned_data = df.dropna().drop_duplicates() # removed duplicates and null values
# confrim
cleaned_data.isnull().sum()

Patient ID        0
Patient Name      0
Age               0
Gender            0
Diagnosis         0
Treatment         0
Medication        0
Admission Date    0
Discharge Date    0
Doctor            0
dtype: int64

In [5]:
cleaned_data.head()

,Patient ID,Patient Name,Age,Gender,Diagnosis,Treatment,Medication,Admission Date,Discharge Date,Doctor
0,12345,John Doe,45,Male,Diabetes,Insulin Therapy,Metformin,2022-01-15,2022-01-30,Dr. Smith
1,23456,Jane Smith,35,Female,Hypertension,Blood Pressure Monitoring,Lisinopril,2022-02-05,2022-02-20,Dr. Johnson
2,34567,Michael Brown,50,Male,Arthritis,Physical Therapy,Naproxen,2022-03-10,2022-03-25,Dr. Williams
3,45678,Emily Davis,28,Female,Allergy,Antihistamines,Fluticasone,2022-04-01,2022-04-15,Dr. Anderson
4,56789,David Wilson,60,Male,Heart Disease,Cardiac Rehabilitation,Aspirin,2022-05-05,2022-05-20,Dr. Martinez

In [8]:
# Convert 'Admission Date' column to datetime format
# check the data type
cleaned_data.dtypes

cleaned_data["Admission Date"] = pd.to_datetime(cleaned_data["Admission Date"])

cleaned_data.dtypes

Patient ID                 int64
Patient Name              object
Age                        int64
Gender                    object
Diagnosis                 object
Treatment                 object
Medication                object
Admission Date    datetime64[ns]
Discharge Date            object
Doctor                    object
dtype: object

In [11]:
# Grouping the data by 'Diagnosis' and calculating the average age for each diagnosis

cleaned_data.columns

grouped_data_by_diagnosis = cleaned_data.groupby("Diagnosis")["Age"].mean()

grouped_data_by_diagnosis

Diagnosis
Allergy             32.500000
Anxiety             39.000000
Arthritis           56.333333
Cancer              48.166667
Depression          41.500000
Diabetes            29.571429
Heart Disease       36.666667
High Cholesterol    52.400000
Hypertension        35.000000
Infection           38.166667
Obesity             41.333333
Stroke              48.000000
Name: Age, dtype: float64

In [12]:
# Grouping the data by 'Gender' and counting the number of patients for each gender

grouped_by_gender_value_patients = cleaned_data.groupby("Gender")["Patient ID"].count()

grouped_by_gender_value_patients

Gender
Female    34
Male      33
Name: Patient ID, dtype: int64

In [13]:
# Load the dataset from the provided URL
data = pd.read_csv('https://afterwork.ai/ds/e/information_technology_713iu.csv')

# Display the dataset to understand its structure
data.head()

,Employee ID,First Name,Last Name,Department,Job Title,Email,Phone Number,Location,Salary,Joining Date
0,1001,Alice,Wong,IT,Software Developer,alicew@example.com,123-456-7890,New York,85000,2020-01-15
1,1002,Bob,Smith,IT,Database Administrator,bobs@example.com,234-567-8901,San Francisco,80000,2019-11-20
2,1003,Charlie,Johnson,IT,Network Engineer,charliej@example.com,345-678-9012,Chicago,90000,2020-03-10
3,1004,Daisy,Lee,IT,System Analyst,daisyl@example.com,456-789-0123,Los Angeles,78000,2018-09-05
4,1005,Edward,Chen,IT,Security Analyst,edwardc@example.com,567-890-1234,Boston,82000,2021-02-28

In [ ]:
# Create a boolean mask to filter employees with a salary greater than 75000

mask = data["Salary"] >75000 # created the boolean mask

masked_filtered_data = data[mask] # filter the data

masked_filtered_data.head() # display the filtered dataset

,Employee ID,First Name,Last Name,Department,Job Title,Email,Phone Number,Location,Salary,Joining Date
0,1001,Alice,Wong,IT,Software Developer,alicew@example.com,123-456-7890,New York,85000,2020-01-15
1,1002,Bob,Smith,IT,Database Administrator,bobs@example.com,234-567-8901,San Francisco,80000,2019-11-20
2,1003,Charlie,Johnson,IT,Network Engineer,charliej@example.com,345-678-9012,Chicago,90000,2020-03-10
3,1004,Daisy,Lee,IT,System Analyst,daisyl@example.com,456-789-0123,Los Angeles,78000,2018-09-05
4,1005,Edward,Chen,IT,Security Analyst,edwardc@example.com,567-890-1234,Boston,82000,2021-02-28

In [18]:
# Filter the dataset based on multiple conditions using logical AND operator

# Load the dataset from the provided URL
df = pd.read_csv('https://afterwork.ai/ds/e/healthcare_1xeq5.csv')
df.head()

filtred_data = df[(df["Age"]<=30) & (df["Diagnosis"]== "Diabetes")]

filtred_data

,Patient ID,Patient Name,Age,Gender,Diagnosis,Treatment,Doctor Name,Admission Date,Discharge Date,Room Number
1,1002,Jane Smith,30,Female,Diabetes,Diet and Exercise,Dr. Johnson,2021-06-02,2021-06-10,202

In [ ]:
# Negating Filters with NOT

filtred_data = df[~(df["Diagnosis"]== "Diabetes") & ~(df["Gender"]=="Female")]

filtred_data

Empty DataFrame
Columns: [Patient ID, Patient Name, Age, Gender, Diagnosis, Treatment, Doctor Name, Admission Date, Discharge Date, Room Number]
Index: []

In [23]:
# Filter out rows where the 'Diagnosis' column is not equal to 'Diabetes'

filtred_data = df[~(df["Diagnosis"]== "Diabetes")]

filtred_data

,Patient ID,Patient Name,Age,Gender,Diagnosis,Treatment,Doctor Name,Admission Date,Discharge Date,Room Number
0,1001,John Doe,45,Male,Hypertension,Medication,Dr. Smith,2021-05-10,2021-05-15,101
2,1003,Michael Johnson,55,Male,Arthritis,Physical Therapy,Dr. Brown,2021-07-15,2021-07-25,305
3,1004,Sarah Lee,40,Female,Migraine,Medication,Dr. Wilson,2021-08-05,2021-08-12,102
4,1005,David Miller,65,Male,Osteoporosis,Calcium Supplements,Dr. Martinez,2021-09-20,2021-09-30,401
5,1006,Emily Davis,28,Female,Anxiety,Counseling,Dr. Adams,2021-10-12,2021-10-20,203
...,...,...,...,...,...,...,...,...,...,...
70,1071,Sofia King,29,Female,Alzheimer's Disease,Memory Therapy,Dr. King,2027-03-03,2027-03-15,418
71,1072,Logan Turner,50,Male,Sleep Apnea,CPAP Machine,Dr. Lopez,2027-04-20,2027-04-28,119
72,1073,Isaac Hill,65,Female,Influenza,Rest and Fluids,Dr. Garcia,2027-05-15,2027-05-25,322
73,1074,Leah Lopez,38,Female,Cancer,Chemotherapy,Dr. Hill,2027-06-10,2027-06-18,120
74,1075,Mila Garcia,25,Female,Anemia,Iron Supplements,Dr. Adams,2027-07-25,2027-07-30,419

In [25]:
# Filter the DataFrame to select rows where the patient's age is greater than 50 or the patient's diagnosis is 'Cancer'

filtred_data_2 = df[(df["Age"]>50) | (df["Diagnosis"]=="Cancer")]
filtred_data_2

,Patient ID,Patient Name,Age,Gender,Diagnosis,Treatment,Doctor Name,Admission Date,Discharge Date,Room Number
2,1003,Michael Johnson,55,Male,Arthritis,Physical Therapy,Dr. Brown,2021-07-15,2021-07-25,305
4,1005,David Miller,65,Male,Osteoporosis,Calcium Supplements,Dr. Martinez,2021-09-20,2021-09-30,401
7,1008,Linda Wilson,60,Female,Heart Disease,Cardiac Rehabilitation,Dr. Garcia,2021-12-03,2021-12-15,103
11,1012,Susan Martinez,70,Female,Alzheimer's Disease,Memory Therapy,Dr. Adams,2022-04-15,2022-04-25,104
14,1015,Mark Evans,58,Male,Cancer,Chemotherapy,Dr. Hill,2022-07-03,2022-07-15,308
17,1018,George Adams,75,Male,Stroke,Rehabilitation Therapy,Dr. Garcia,2022-10-10,2022-10-18,206
18,1019,Carolyn Perez,55,Female,Arthritis,Physical Therapy,Dr. Brown,2022-11-05,2022-11-12,309
21,1022,Daniel King,52,Male,Heart Disease,Cardiac Rehabilitation,Dr. Lee,2023-02-08,2023-02-18,209
22,1023,Martha Hill,68,Female,Osteoporosis,Calcium Supplements,Dr. Perez,2023-03-03,2023-03-15,310
25,1026,Jackie Brown,60,Male,Obesity,Diet and Exercise,Dr. Turner,2023-06-10,2023-06-18,210
29,1030,Andrew Perez,50,Male,Cancer,Chemotherapy,Dr. Garcia,2023-10-15,2023-10-25,211
30,1031,Emma Scott,65,Female,Anemia,Iron Supplements,Dr. Brown,2023-11-10,2023-11-18,312
32,1033,Oliver Martinez,70,Male,Stroke,Rehabilitation Therapy,Dr. Perez,2024-01-10,2024-01-18,408
35,1036,Max Hill,58,Male,Depression,Medication,Dr. Turner,2024-04-15,2024-04-25,110
38,1039,Harper Brown,75,Female,Sleep Apnea,CPAP Machine,Dr. Lopez,2024-07-03,2024-07-15,314
40,1041,Amelia Wilson,55,Female,Cancer,Chemotherapy,Dr. Brown,2024-09-15,2024-09-25,410
43,1044,Liam Adams,52,Male,Stroke,Rehabilitation Therapy,Dr. Adams,2024-12-20,2024-12-30,112
44,1045,Ava Martinez,68,Female,Arthritis,Physical Therapy,Dr. Turner,2025-01-12,2025-01-20,411
47,1048,Logan Lopez,60,Male,Heart Disease,Cardiac Rehabilitation,Dr. Garcia,2025-04-20,2025-04-28,113
51,1052,Lucas Perez,50,Male,Cancer,Chemotherapy,Dr. Adams,2025-08-12,2025-08-20,114
52,1053,Aria Scott,65,Female,Anemia,Iron Supplements,Dr. Turner,2025-09-20,2025-09-28,413
54,1055,Noah Wilson,70,Male,Stroke,Rehabilitation Therapy,Dr. Lopez,2025-11-10,2025-11-18,318
57,1058,Elijah Scott,52,Male,Depression,Medication,Dr. Turner,2026-02-05,2026-02-12,218
58,1059,Sofia King,68,Female,Heart Disease,Cardiac Rehabilitation,Dr. Adams,2026-03-20,2026-03-30,319
61,1062,Leah Lopez,75,Female,Influenza,Rest and Fluids,Dr. Garcia,2026-06-08,2026-06-18,219
62,1063,Mila Garcia,47,Male,Cancer,Chemotherapy,Dr. Hill,2026-07-03,2026-07-15,320
63,1064,Lucas Brown,55,Female,Anemia,Iron Supplements,Dr. Adams,2026-08-20,2026-08-30,117
66,1067,Noah Wilson,65,Male,Arthritis,Physical Therapy,Dr. Lopez,2026-11-05,2026-11-12,118
68,1069,Ava Perez,58,Male,Depression,Medication,Dr. Hill,2027-01-12,2027-01-20,321
72,1073,Isaac Hill,65,Female,Influenza,Rest and Fluids,Dr. Garcia,2027-05-15,2027-05-25,322
73,1074,Leah Lopez,38,Female,Cancer,Chemotherapy,Dr. Hill,2027-06-10,2027-06-18,120

In [26]:

#String Extraction Filtering

string_filtered = df[df["Treatment"].str.contains("Therapy")]

string_filtered

,Patient ID,Patient Name,Age,Gender,Diagnosis,Treatment,Doctor Name,Admission Date,Discharge Date,Room Number
2,1003,Michael Johnson,55,Male,Arthritis,Physical Therapy,Dr. Brown,2021-07-15,2021-07-25,305
11,1012,Susan Martinez,70,Female,Alzheimer's Disease,Memory Therapy,Dr. Adams,2022-04-15,2022-04-25,104
17,1018,George Adams,75,Male,Stroke,Rehabilitation Therapy,Dr. Garcia,2022-10-10,2022-10-18,206
18,1019,Carolyn Perez,55,Female,Arthritis,Physical Therapy,Dr. Brown,2022-11-05,2022-11-12,309
26,1027,Olivia White,35,Female,Alzheimer's Disease,Memory Therapy,Dr. King,2023-07-25,2023-07-30,311
32,1033,Oliver Martinez,70,Male,Stroke,Rehabilitation Therapy,Dr. Perez,2024-01-10,2024-01-18,408
33,1034,Isabella Turner,38,Female,Arthritis,Physical Therapy,Dr. Scott,2024-02-05,2024-02-12,212
37,1038,Owen Garcia,47,Male,Alzheimer's Disease,Memory Therapy,Dr. Hill,2024-06-08,2024-06-18,213
43,1044,Liam Adams,52,Male,Stroke,Rehabilitation Therapy,Dr. Adams,2024-12-20,2024-12-30,112
44,1045,Ava Martinez,68,Female,Arthritis,Physical Therapy,Dr. Turner,2025-01-12,2025-01-20,411
48,1049,Isaac Garcia,35,Male,Alzheimer's Disease,Memory Therapy,Dr. Hill,2025-05-15,2025-05-25,412
54,1055,Noah Wilson,70,Male,Stroke,Rehabilitation Therapy,Dr. Lopez,2025-11-10,2025-11-18,318
55,1056,Liam Lee,38,Female,Arthritis,Physical Therapy,Dr. Garcia,2025-12-05,2025-12-15,115
59,1060,Logan Turner,32,Female,Alzheimer's Disease,Memory Therapy,Dr. King,2026-04-15,2026-04-25,116
65,1066,Ella Adams,29,Female,Stroke,Rehabilitation Therapy,Dr. King,2026-10-10,2026-10-18,320
66,1067,Noah Wilson,65,Male,Arthritis,Physical Therapy,Dr. Lopez,2026-11-05,2026-11-12,118
70,1071,Sofia King,29,Female,Alzheimer's Disease,Memory Therapy,Dr. King,2027-03-03,2027-03-15,418

In [27]:
# Filter the dataset to extract only the patients with a specific diagnosis, for example, 'Depression'

filtered_depression = df[df["Diagnosis"].str.contains("Depression")]

filtered_depression

,Patient ID,Patient Name,Age,Gender,Diagnosis,Treatment,Doctor Name,Admission Date,Discharge Date,Room Number
6,1007,Robert Brown,50,Male,Depression,Medication,Dr. White,2021-11-08,2021-11-18,306
20,1021,Rebecca Turner,29,Female,Depression,Medication,Dr. Martinez,2023-01-12,2023-01-20,405
35,1036,Max Hill,58,Male,Depression,Medication,Dr. Turner,2024-04-15,2024-04-25,110
46,1047,Sofia Hill,45,Female,Depression,Medication,Dr. Lopez,2025-03-03,2025-03-15,316
57,1058,Elijah Scott,52,Male,Depression,Medication,Dr. Turner,2026-02-05,2026-02-12,218
68,1069,Ava Perez,58,Male,Depression,Medication,Dr. Hill,2027-01-12,2027-01-20,321

In [29]:
#Date Range Filtering

# Convert 'Admission Date' and 'Discharge Date' columns to datetime format
df['Admission Date'] = pd.to_datetime(df['Admission Date'])
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])

# Define the date range for filtering
start_date = '2021-08-01'
end_date = '2022-08-31'


filtered_by_date = df.query("`Admission Date`>=@start_date and `Discharge Date`<=@end_date")

filtered_by_date

,Patient ID,Patient Name,Age,Gender,Diagnosis,Treatment,Doctor Name,Admission Date,Discharge Date,Room Number
3,1004,Sarah Lee,40,Female,Migraine,Medication,Dr. Wilson,2021-08-05,2021-08-12,102
4,1005,David Miller,65,Male,Osteoporosis,Calcium Supplements,Dr. Martinez,2021-09-20,2021-09-30,401
5,1006,Emily Davis,28,Female,Anxiety,Counseling,Dr. Adams,2021-10-12,2021-10-20,203
6,1007,Robert Brown,50,Male,Depression,Medication,Dr. White,2021-11-08,2021-11-18,306
7,1008,Linda Wilson,60,Female,Heart Disease,Cardiac Rehabilitation,Dr. Garcia,2021-12-03,2021-12-15,103
8,1009,James Taylor,35,Male,Allergies,Allergy Shots,Dr. Lee,2022-01-10,2022-01-18,402
9,1010,Amy Clark,42,Female,Asthma,Inhalers,Dr. Perez,2022-02-05,2022-02-12,204
10,1011,William Rodriguez,48,Male,Obesity,Diet and Exercise,Dr. Scott,2022-03-20,2022-03-30,307
11,1012,Susan Martinez,70,Female,Alzheimer's Disease,Memory Therapy,Dr. Adams,2022-04-15,2022-04-25,104
12,1013,Christopher Young,38,Male,Sleep Apnea,CPAP Machine,Dr. Turner,2022-05-12,2022-05-20,403
13,1014,Amanda Harris,25,Female,Influenza,Rest and Fluids,Dr. King,2022-06-08,2022-06-18,205
14,1015,Mark Evans,58,Male,Cancer,Chemotherapy,Dr. Hill,2022-07-03,2022-07-15,308
15,1016,Karen Baker,32,Female,Anemia,Iron Supplements,Dr. Lopez,2022-08-20,2022-08-30,105