In [2]:
# import libraries

import pandas as pd

from datetime import datetime as dt

from sklearn.preprocessing import OrdinalEncoder

**Challange 1**

Calculate the mode of the 'Quantity' column in the provided dataset from the URL: https://afterwork.ai/ds/ch/operations_lfuyn.csv. You can use the Pandas function 'mode()' to calculate the mode of a specific column in a dataset.

In [7]:
# Load the dataset from the provided URL
df = pd.read_csv('https://afterwork.ai/ds/ch/operations_lfuyn.csv')
df.head()

   Order ID Product Name  ... Shipping Address       Status
0      1001     Keyboard  ...      123 Main St    Delivered
1      1002        Mouse  ...       456 Elm St    Delivered
2      1003      Monitor  ...       789 Oak St  In Progress
3      1004         Desk  ...      321 Pine St    Delivered
4      1005        Chair  ...     654 Cedar St    Delivered

[5 rows x 10 columns]

In [ ]:
# Calculate the mode of the 'Quantity' column

summary = df["Quantity"].agg(["mode"])

summary

   mode
0     1

In [ ]:
#1. Calculating Summary Statistics
df["Quantity"].describe()

count    75.000000
mean      1.546667
std       0.826803
min       1.000000
25%       1.000000
50%       1.000000
75%       2.000000
max       5.000000
Name: Quantity, dtype: float64

In [ ]:
# Drop Shipping Address and Discount columns

df.drop(['Shipping Address','Discount'],axis = 1, inplace = True)

# Display the DataFrame after dropping the column
df.head()

   Order ID Product Name  ...  Order Date       Status
0      1001     Keyboard  ...  2021-05-10    Delivered
1      1002        Mouse  ...  2021-05-12    Delivered
2      1003      Monitor  ...  2021-05-15  In Progress
3      1004         Desk  ...  2021-05-18    Delivered
4      1005        Chair  ...  2021-05-20    Delivered

[5 rows x 8 columns]


Challenge 2

Given the dataset from the URL: https://afterwork.ai/ds/ch/operations_xvmul.csv, create a code snippet that sorts the data by the 'Total Cost' column in descending order. This will help in identifying the most expensive items in the dataset. Use the 'sort_values()' method in Pandas to achieve this.

In [ ]:
# Loading the dataset from the provided URL

data = pd.read_csv("https://afterwork.ai/ds/ch/operations_xvmul.csv")

# Sorting the DataFrame by the 'Total Cost' column in descending order

data.sort_values(by=["Total Cost"], ascending= False).head()

    Order ID         Product Name  ...     Location        Date
3       1004              Monitor  ...  Los Angeles  2021-03-15
28      1029         Office Chair  ...     New York  2021-10-28
9       1010  External Hard Drive  ...       Boston  2021-10-18
74      1075  External Hard Drive  ...        Miami  2021-02-28
18      1019           Desk Chair  ...      Detroit  2021-07-20

[5 rows x 10 columns]

**Challenge 3**

Given the dataset from the URL: https://afterwork.ai/ds/ch/operations_r2xlo.csv, create a code snippet to remove duplicate entries based on the 'Order ID' and 'Date' columns.

In [18]:
data_3 = pd.read_csv("https://afterwork.ai/ds/ch/operations_r2xlo.csv")

data_3.duplicated(subset= ["Category"]).sum()


no_duplicate = data_3.drop_duplicates()

rows,columns = no_duplicate.shape

print(f"rows: {rows}\ncolumns: {columns}")

rows: 75
columns: 10

**Challenge 4**

Write a Python code snippet using Pandas to group the data by both 'Category' and 'Brand' to analyze the total price and stock quantity. Use the dataset from the following URL: https://afterwork.ai/ds/ch/operations_kr4od.csv

In [ ]:
# Loading the dataset from the provided URL
df = pd.read_csv('https://afterwork.ai/ds/e/products_wkc5o.csv')

# Aggregating data with multiple grouping columns

df.groupby(["Category","Brand"])[["Price","Stock Quantity"]].sum().T

Category       Accessories                ... Office Supplies
Brand               Adidas Casio Contigo  ...           Quill Staples Texas Instruments
Price                   50   100      15  ...              50      35                20
Stock Quantity         200   150     400  ...             500     500               300

[2 rows x 57 columns]

**Challenge 5**

Given the dataset provided at the URL: https://afterwork.ai/ds/ch/operations_yux8o.csv, write a Python script using Pandas to search for all rows where the 'Delivery Status' column contains the value 'In Transit'. Once you have filtered the dataset, calculate the total quantity of products that are currently 'In Transit'.

In [23]:
# Load the dataset from the provided URL
df = pd.read_csv('https://afterwork.ai/ds/ch/operations_yux8o.csv')

# Previw the dataset to understand its structure
df.head()

   Order ID Product Name         Category  ...  Delivery Status     Location  Manager
0      1001     Keyboard      Electronics  ...        Delivered     New York     John
1      1002        Mouse      Electronics  ...       In Transit  Los Angeles    Sarah
2      1003      Printer      Electronics  ...        Delivered      Chicago  Michael
3      1004      Monitor      Electronics  ...       In Transit        Miami    Emily
4      1005         Desk  Office Supplies  ...        Delivered      Houston    David

[5 rows x 10 columns]

In [ ]:
# Search for all rows where 'Delivery Status' column contains 'In Transit'

filtered_data = df[df["Delivery Status"].str.contains("In Transit", case = False)]

# Calculate the total quantity of products that are currently 'In Transit'
# Display the total quantity of products that are currently 'In Transit'

print(filtered_data['Quantity'].agg(['sum']))

sum    230
Name: Quantity, dtype: int64