In [1]:
# Import pandas for data manipulation
import pandas as pd

In [ ]:
# Load the dataset from the provided URL
df = pd.read_csv('https://afterwork.ai/ds/e/banking_0bz3y.csv')
print(df.head())

# Grouping the data by 'Branch' and calculating the total 'Amount' for each branch

grouped_by_branch = df.groupby("Branch")["Amount"].sum()

# Displaying the total amount for each branch
grouped_by_branch

   Customer ID Account Number Transaction Type  Amount Transaction Date  \
0         1001      ACCT12345          Deposit     500       2021-05-10
1         1002      ACCT54321       Withdrawal     100       2021-05-12
2         1003      ACCT98765         Transfer     200       2021-05-15
3         1004      ACCT24680          Deposit     300       2021-05-18
4         1005      ACCT13579       Withdrawal      50       2021-05-20

     Branch  ATM Location Transaction Category Merchant Name Card Type
0  Branch A           NaN               Salary           NaN     Debit
1  Branch B           NaN      Cash Withdrawal           NaN     Debit
2  Branch C           NaN             Transfer      XYZ Bank     Debit
3  Branch A           NaN               Salary           NaN     Debit
4  Branch B           NaN      Cash Withdrawal           NaN     Debit

Branch
Branch A    7750
Branch B    1965
Branch C    4500
Name: Amount, dtype: int64

In [ ]:
# returns the columns
print(df.columns)

# Grouping the data by 'Transaction Type' and calculating the total 'Amount' for each transaction type

grouped_by_transaction_type = df.groupby("Transaction Type")["Amount"].sum()

# Displaying the total amount for each transaction type
print(grouped_by_transaction_type)

Index(['Customer ID', 'Account Number', 'Transaction Type', 'Amount',
       'Transaction Date', 'Branch', 'ATM Location', 'Transaction Category',
       'Merchant Name', 'Card Type'],
      dtype='object')
Transaction Type
Deposit       7750
Transfer      4500
Withdrawal    1965
Name: Amount, dtype: int64

In [9]:
pivot_table_1 = df.pivot_table(index=["Transaction Type","Card Type","Branch","Account Number"],values=["Amount"],aggfunc="sum")

print(pivot_table_1)

                                                    Amount
Transaction Type Card Type Branch   Account Number
Deposit          Debit     Branch A ACCT12345          500
                                    ACCT19824          250
                                    ACCT24680          300
                                    ACCT28470          200
                                    ACCT35791          350
...                                                    ...
Withdrawal       Debit     Branch B ACCT92816           80
                                    ACCT92817           80
                                    ACCT92818           70
                                    ACCT92819           70
                                    ACCT94628           90

[75 rows x 1 columns]

In [22]:
# Selecting a range of rows and columns by label for data transformation

#method 1

df1 = df.iloc[:11,0:3]

print(df1)
print("====="*15)
#method 2

df2 =df.loc[:10,['Customer ID','Account Number','Transaction Type']]

print(df2)

    Customer ID Account Number Transaction Type
0          1001      ACCT12345          Deposit
1          1002      ACCT54321       Withdrawal
2          1003      ACCT98765         Transfer
3          1004      ACCT24680          Deposit
4          1005      ACCT13579       Withdrawal
5          1006      ACCT86420         Transfer
6          1007      ACCT97531          Deposit
7          1008      ACCT75309       Withdrawal
8          1009      ACCT46802         Transfer
9          1010      ACCT35791          Deposit
10         1011      ACCT90246       Withdrawal
===========================================================================
    Customer ID Account Number Transaction Type
0          1001      ACCT12345          Deposit
1          1002      ACCT54321       Withdrawal
2          1003      ACCT98765         Transfer
3          1004      ACCT24680          Deposit
4          1005      ACCT13579       Withdrawal
5          1006      ACCT86420         Transfer
6          1007      ACCT97531          Deposit
7          1008      ACCT75309       Withdrawal
8          1009      ACCT46802         Transfer
9          1010      ACCT35791          Deposit
10         1011      ACCT90246       Withdrawal

In [23]:
#Arbitrary Imputation

# Check for missing values

missing_values_check = df.isnull().sum()

print(missing_values_check)

Customer ID              0
Account Number           0
Transaction Type         0
Amount                   0
Transaction Date         0
Branch                   0
ATM Location            75
Transaction Category     0
Merchant Name           50
Card Type                0
dtype: int64

In [37]:
# Perform Arbitrary Imputation by replacing missing values with a specific value (e.g., 0)

df[["ATM Location","Merchant Name"]]= df[["ATM Location","Merchant Name"]].fillna("Not provided")

not_provided = df[df["Merchant Name"].str.contains("Not provided")|df["ATM Location"].str.contains("Not provided")]

print(not_provided)

missing = df.isnull().sum()
print(missing)

    Customer ID Account Number Transaction Type  Amount Transaction Date  \
0          1001      ACCT12345          Deposit     500       2021-05-10
1          1002      ACCT54321       Withdrawal     100       2021-05-12
2          1003      ACCT98765         Transfer     200       2021-05-15
3          1004      ACCT24680          Deposit     300       2021-05-18
4          1005      ACCT13579       Withdrawal      50       2021-05-20
..          ...            ...              ...     ...              ...
70         1071      ACCT79210       Withdrawal      90       2021-11-05
71         1072      ACCT61522         Transfer     180       2021-11-08
72         1073      ACCT37491          Deposit     200       2021-11-10
73         1074      ACCT92812       Withdrawal      60       2021-11-12
74         1075      ACCT16391         Transfer     120       2021-11-15

      Branch  ATM Location Transaction Category Merchant Name Card Type
0   Branch A  Not provided               Salary  Not provided     Debit
1   Branch B  Not provided      Cash Withdrawal  Not provided     Debit
2   Branch C  Not provided             Transfer      XYZ Bank     Debit
3   Branch A  Not provided               Salary  Not provided     Debit
4   Branch B  Not provided      Cash Withdrawal  Not provided     Debit
..       ...           ...                  ...           ...       ...
70  Branch B  Not provided      Cash Withdrawal  Not provided     Debit
71  Branch C  Not provided             Transfer      GHI Bank     Debit
72  Branch A  Not provided               Salary  Not provided     Debit
73  Branch B  Not provided      Cash Withdrawal  Not provided     Debit
74  Branch C  Not provided             Transfer      JKL Bank     Debit

[75 rows x 10 columns]
Customer ID             0
Account Number          0
Transaction Type        0
Amount                  0
Transaction Date        0
Branch                  0
ATM Location            0
Transaction Category    0
Merchant Name           0
Card Type               0
dtype: int64

In [ ]:
#Filtering using the Query Method

filtered_data = df.query("`ATM Location` == 'Not provided'")
filtered_data.head()

,Customer ID,Account Number,Transaction Type,Amount,Transaction Date,Branch,ATM Location,Transaction Category,Merchant Name,Card Type
0,1001,ACCT12345,Deposit,500,2021-05-10,Branch A,Not provided,Salary,Not provided,Debit
1,1002,ACCT54321,Withdrawal,100,2021-05-12,Branch B,Not provided,Cash Withdrawal,Not provided,Debit
2,1003,ACCT98765,Transfer,200,2021-05-15,Branch C,Not provided,Transfer,XYZ Bank,Debit
3,1004,ACCT24680,Deposit,300,2021-05-18,Branch A,Not provided,Salary,Not provided,Debit
4,1005,ACCT13579,Withdrawal,50,2021-05-20,Branch B,Not provided,Cash Withdrawal,Not provided,Debit

In [41]:
# Load the dataset from the provided URL
dataset2 = pd.read_csv('https://afterwork.ai/ds/ch/banking_ih4j9.csv')
dataset2.head()

,Account Number,Account Type,Account Balance,Last Transaction Amount,Last Transaction Date,Branch Code,Customer ID,Customer Name,Customer Age,Customer Address
0,1001,Savings,5000,100,2021-09-15,1,2001,John Doe,35,123 Main St
1,1002,Checking,2500,50,2021-09-20,2,2002,Jane Smith,28,456 Elm St
2,1003,Investment,10000,200,2021-09-10,3,2003,Michael Johnson,40,789 Oak St
3,1004,Savings,7000,150,2021-09-25,1,2004,Sarah Brown,45,321 Pine St
4,1005,Checking,3000,75,2021-09-30,2,2005,Emily Davis,30,654 Cedar St

In [45]:
# Filtering the dataset to show only accounts where customer age is less than or equal to 40 and Balance is greater than 5000

filtered_by_age = dataset2.query("(`Customer Age`<=40) and `Account Balance`>5000")

filtered_by_age.head()

,Account Number,Account Type,Account Balance,Last Transaction Amount,Last Transaction Date,Branch Code,Customer ID,Customer Name,Customer Age,Customer Address
2,1003,Investment,10000,200,2021-09-10,3,2003,Michael Johnson,40,789 Oak St
6,1007,Savings,6000,120,2021-09-28,1,2007,Lisa Miller,38,135 Birch St
12,1013,Savings,9000,180,2021-09-26,1,2013,Grace Clark,39,246 Cherry St
19,1020,Checking,5500,150,2021-09-16,2,2020,Isabella Baker,37,468 Plum St
22,1023,Checking,6000,180,2021-09-13,2,2023,Liam Murphy,39,864 Honeydew St

In [46]:
#Statistical Descriptive Analysis in Pandas

dataset2["Account Balance"].describe()

count       50.000000
mean     20370.000000
std      20639.473277
min       2500.000000
25%       7125.000000
50%      11500.000000
75%      20750.000000
max      80000.000000
Name: Account Balance, dtype: float64

In [50]:
#Sorting and Filtering Data based on Multiple Criteria

dataset2.sort_values(by = ["Account Balance","Customer Age"],ascending=(False,True)).head()

,Account Number,Account Type,Account Balance,Last Transaction Amount,Last Transaction Date,Branch Code,Customer ID,Customer Name,Customer Age,Customer Address
47,1048,Investment,80000,1600,2021-09-10,3,2048,Elizabeth Collins,115,987 Blueberry St
44,1045,Investment,75000,1500,2021-09-08,3,2045,Charlie Hughes,110,579 Strawberry St
41,1042,Investment,70000,1400,2021-09-09,3,2042,Ella Collins,105,987 Raspberry St
38,1039,Investment,65000,1300,2021-09-07,3,2039,Avery Hughes,100,579 Blueberry St
35,1036,Investment,60000,1200,2021-09-06,3,2036,Harper Collins,95,987 Strawberry St

In [52]:
# Filtering data based on multiple criteria: Account Type is 'Savings' and Account Balance is greater than 7000

dataset2[(dataset2["Account Type"] == "Savings") & (dataset2["Account Balance"]>7000)]

,Account Number,Account Type,Account Balance,Last Transaction Amount,Last Transaction Date,Branch Code,Customer ID,Customer Name,Customer Age,Customer Address
9,1010,Savings,8000,200,2021-09-22,1,2010,Mark Taylor,48,753 Orange St
12,1013,Savings,9000,180,2021-09-26,1,2013,Grace Clark,39,246 Cherry St
15,1016,Savings,10000,250,2021-09-24,1,2016,Robert Adams,47,579 Banana St
18,1019,Savings,11000,300,2021-09-19,1,2019,Sophia Evans,50,357 Peach St
21,1022,Savings,12000,300,2021-09-27,1,2022,Ella Morris,42,753 Cantaloupe St
24,1025,Savings,13000,350,2021-09-23,1,2025,Noah Cooper,45,357 Guava St
27,1028,Savings,14000,400,2021-09-25,1,2028,Chloe Hayes,48,753 Persimmon St
30,1031,Savings,15000,400,2021-09-29,1,2031,Daniel Price,50,357 Kumquat St
33,1034,Savings,16000,450,2021-09-26,1,2034,Amelia Ward,52,753 Blueberry St
36,1037,Savings,17000,500,2021-09-24,1,2037,Evelyn Cooper,55,357 Raspberry St
39,1040,Savings,18000,500,2021-09-25,1,2040,Riley Bell,58,753 Cranberry St
42,1043,Savings,19000,550,2021-09-27,1,2043,Henry Cooper,60,357 Blueberry St
45,1046,Savings,20000,600,2021-09-26,1,2046,Victoria Bell,63,753 Raspberry St
48,1049,Savings,21000,650,2021-09-28,1,2049,Matthew Cooper,65,357 Blackberry St

In [ ]:

# Load the dataset from the provided URL
df = pd.read_csv('https://afterwork.ai/ds/e/banking_97kb8.csv')


#Encoding Data using the Map Function
# Define a mapping dictionary for encoding Account Type to numeric values
gender_map = {"Male":0,"Female":1}

# Apply the map function to encode Account Type column using the mapping dictionary
df["Gender_encoded"] = df["Gender"].map(gender_map)

df.head()

,Customer ID,Gender,Age,Account Type,Account Balance,Transaction Type,Transaction Amount,Transaction Date,Branch Location,Loan Status,Gender_encoded
0,1001,Male,35,Savings,5000,Deposit,100,2021-01-05,New York,Approved,0
1,1002,Female,28,Checking,3000,Withdrawal,50,2021-02-10,Los Angeles,Rejected,1
2,1003,Male,45,Savings,7000,Transfer,200,2021-03-15,Chicago,Approved,0
3,1004,Female,32,Checking,4000,Deposit,150,2021-04-20,Miami,Approved,1
4,1005,Male,50,Savings,6000,Withdrawal,75,2021-05-25,San Francisco,Rejected,0

In [55]:
# Define a mapping dictionary for encoding Account Type to numeric values

loan_status_map = {"Approved":1,
                   "Rejected":0}


# Apply the map function to encode Account Type column using the mapping dictionary

df["loan_status_encoded"] = df["Loan Status"].map(loan_status_map)

# Preview the resulting dataframe

df.head()

,Customer ID,Gender,Age,Account Type,Account Balance,Transaction Type,Transaction Amount,Transaction Date,Branch Location,Loan Status,Gender_encoded,loan_status_encoded
0,1001,Male,35,Savings,5000,Deposit,100,2021-01-05,New York,Approved,0,1
1,1002,Female,28,Checking,3000,Withdrawal,50,2021-02-10,Los Angeles,Rejected,1,0
2,1003,Male,45,Savings,7000,Transfer,200,2021-03-15,Chicago,Approved,0,1
3,1004,Female,32,Checking,4000,Deposit,150,2021-04-20,Miami,Approved,1,1
4,1005,Male,50,Savings,6000,Withdrawal,75,2021-05-25,San Francisco,Rejected,0,0

In [ ]:
#Random Sampling for Data Analysis
# Rows with a higher value in the "loan_status_encoded" column are more likely to be picked
# random_state =1 :ensure that the exact same 5 rows are chosen every single time you run the code.


sample_data = df.sample(n=5,weights="loan_status_encoded",random_state=1)
sample_data

,Customer ID,Gender,Age,Account Type,Account Balance,Transaction Type,Transaction Amount,Transaction Date,Branch Location,Loan Status,Gender_encoded,loan_status_encoded
25,1026,Female,35,Checking,4100,Withdrawal,60,2023-02-10,Baltimore,Approved,1,1
44,1045,Male,34,Savings,5900,Transfer,160,2024-09-15,Annapolis,Approved,0,1
0,1001,Male,35,Savings,5000,Deposit,100,2021-01-05,New York,Approved,0,1
18,1019,Male,49,Savings,8000,Deposit,200,2022-07-05,Indianapolis,Approved,0,1
8,1009,Male,48,Savings,7500,Transfer,250,2021-09-15,Seattle,Approved,0,1